theme:
  - hugo-cloak-email
  - blowfish
baseURL: https://mkcg.pl/
defaultContentLanguage: en
pluralizeListTitles: false
enableRobotsTXT: true
summaryLength: 0
buildDrafts: false
buildFuture: false
enableEmoji: true
pagination:
  pagerSize: 100
imaging:
  anchor: Center
taxonomies:
  tag: tags
  category: categories
  author: authors
  series: series
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
outputs:
  home:
    - HTML
    - RSS
    - JSON
related:
  threshold: 0
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 100
    - name: series
      weight: 50
    - name: authors
      weight: 20
    - name: date
      weight: 10
    - applyFilter: false
      name: fragmentrefs
      type: fragments
      weight: 10
languages:
  en:
    languageCode: en
    languageName: English
    contentDir: "content/en"
    weight: 1
    title: MKCG.PL
    params:
      displayName: EN
      isoCode: en
      rtl: false
      dateFormat: 2 January 2006
      author:
        name: Marcin Kowalski
        email: marcin@mkcg.pl
        image: img/marcin_kowalski.jpg
        imageQuality: 96
        headline: Strategic AI Consultant ðŸ—² Former CTO
        bio: Strategic AI Consultant ðŸ—² Former CTO
        links:
          - email: mailto:marcin@mkcg.pl
          - github: https://github.com/mrkowalski
          - linkedin: https://linkedin.com/in/marcinkowalski
